import { useRef, useState } from 'react';
import { pipeline, TextStreamer } from '@huggingface/transformers';
let generatorPromise: Promise<any> | null = null;
async function getGenerator(){
 if(!generatorPromise) generatorPromise = pipeline('text-generation','onnx-community/SmolLM2-135M-Instruct-ONNX',{dtype:'q4',device:'wasm'}).catch(e=>{generatorPromise=null;throw e});
 return generatorPromise;
}
export default function AI(){const [messages,setMessages]=useState<{r:string;t:string}[]>([]);const [input,setInput]=useState('');const [busy,setBusy]=useState(false);const [status,setStatus]=useState('Model not loaded');const outputRef=useRef('');
 async function send(){const q=input.trim();if(!q||busy)return;setInput('');setMessages(m=>[...m,{r:'You',t:q}]);setBusy(true);setStatus('Loading local AI…');try{const g=await getGenerator();setStatus('Generating locally on this device…');outputRef.current='';const streamer=new TextStreamer(g.tokenizer,{skip_prompt:true,skip_special_tokens:true,callback_function:(x:string)=>{outputRef.current+=x;setMessages(m=>{const copy=[...m];const last=copy[copy.length-1];if(last?.r==='NOVOS AI')copy[copy.length-1]={...last,t:outputRef.current};else copy.push({r:'NOVOS AI',t:outputRef.current});return copy})}});await g([{role:'user',content:q}],{max_new_tokens:160,do_sample:true,temperature:.7,streamer});setStatus('Ready')}catch(e){setStatus('AI error — NOVOS is still running.');setMessages(m=>[...m,{r:'NOVOS AI',t:`The local model could not run. ${(e as Error)?.message||'Unknown error'}`}])}finally{setBusy(false)}}return <div className="h-full flex flex-col text-white"><div className="p-4 border-b border-cyan-500/10"><h2 className="font-bold">🤖 NOVOS AI</h2><p className="text-white/35 text-xs">SmolLM2 135M · Transformers.js 3.8.1 · ONNX/WASM · q4 · no API key</p><p className="text-cyan-400/60 text-[10px] mt-1">{status}</p></div><div className="flex-1 overflow-auto p-4 space-y-3">{messages.map((m,i)=><div key={i} className="glass-light rounded-xl p-3"><p className="text-cyan-400 text-xs mb-1">{m.r}</p><p className="text-sm whitespace-pre-wrap">{m.t}</p></div>)}</div><form onSubmit={e=>{e.preventDefault();send()}} className="p-3 flex gap-2"><input value={input} onChange={e=>setInput(e.target.value)} disabled={busy} className="flex-1 bg-white/5 border border-cyan-500/20 rounded-xl px-3 py-2 outline-none" placeholder="Ask NOVOS AI..."/><button disabled={busy} className="px-4 rounded-xl bg-cyan-500/20 border border-cyan-500/30">{busy?'…':'Send'}</button></form></div>}
